### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by FerdinandBeaman** [learn-co-curriculum/dsc-resampling-methods-lab#6]
## Link to Canvas

https://learning.flatironschool.com/courses/4348/assignments/140703?module_item_id=293353

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X] Other (explain below)

## Describe the Issue
Just so you know, there are a number of instances where the word "then" in used instead of "than" on this page. 
E.x.: "...the difference of the means of resampled samples is greater then or equal to the difference...
### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by christine-egan42** [comment]
edited to correct then to than
