### ISSUE TITLE
Simple math error

### ISSUE THREAD

**Issue by MNLKuzmin** [learn-co-curriculum/dsc-resampling-methods-lab#7]
## Link to Canvas

https://learning.flatironschool.com/courses/5316/assignments/184375?module_item_id=408350

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X] Other (explain below)

### Source

```
$\mu_a - \mu_b = \frac{5}{3} - 2 = \frac{1}{2}$
```

### Concern

Basically in the markdown is stated that  5/3 - 2 = 1/2

## (Optional) Proposed Solution

5/3 - 2 = - 1/3

## What OS Are You Using?

- [X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
fixed with [b2af6f7](https://github.com/learn-co-curriculum/dsc-resampling-methods-lab/commit/b2af6f7c5ed847e0bbbb39bb8f2be16f8b952429)
